# Configuración para SonarQube/SonarCloud
sonar.projectKey=devjUtec_portal-servicios-sociales
sonar.organization=devjutec
sonar.projectName=Servicios Sociales API
sonar.projectVersion=1.0

# Rutas de código
sonar.sources=src
sonar.tests=test
sonar.exclusions=node_modules/**, dist/**, **/*.spec.ts, prisma/**, test/**

# Lenguajes
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.typescript.tsconfigPath=tsconfig.json
sonar.sourceEncoding=UTF-8
